<a href="https://colab.research.google.com/github/subbuvidyasekar/ML_Learn/blob/master/TF_img_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf


In [7]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.12713319, -0.7777933 ,  0.41536015, -0.21173593, -0.6785277 ,
         0.10245205, -0.1570191 , -0.6683758 , -0.37665945,  0.23266296]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.10246025, 0.05345365, 0.17626144, 0.0941484 , 0.05903205,
        0.128903  , 0.09944344, 0.05963439, 0.07983394, 0.14682937]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.048695

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4903 - accuracy: 0.8544
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1532 - accuracy: 0.9556
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1109 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0889 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0746 - accuracy: 0.9763


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0770 - accuracy: 0.9767


[0.07699374854564667, 0.9767000079154968]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.67314440e-07, 6.09090944e-10, 1.37889435e-06, 7.68075115e-05,
        2.42406199e-11, 2.58244768e-08, 3.34945525e-14, 9.99921560e-01,
        1.18898615e-08, 1.30991396e-07],
       [9.62515068e-10, 6.27024856e-05, 9.99903917e-01, 3.24299108e-05,
        7.42432981e-18, 2.32192985e-08, 7.15480952e-10, 9.78043465e-14,
        9.44839940e-07, 3.72011449e-15],
       [2.21182930e-07, 9.99020338e-01, 3.32413736e-04, 9.43207306e-06,
        8.75355090e-06, 1.33325398e-06, 2.93011708e-05, 2.77810934e-04,
        3.19824321e-04, 5.24717393e-07],
       [9.99970198e-01, 8.81595597e-09, 9.34475520e-06, 2.84582143e-07,
        1.64919385e-08, 4.15701652e-06, 1.92024550e-06, 8.62670731e-06,
        5.36428111e-08, 5.25601899e-06],
       [4.87441639e-07, 5.53954536e-08, 1.81170822e-06, 1.08498712e-08,
        9.97647703e-01, 1.13968561e-07, 2.15707658e-07, 3.24646717e-05,
        9.47690921e-07, 2.31628306e-03]], dtype=float32)>